name:                coding-challenges-hs
version:             0.1.0.0
github:              "githubuser/coding-challenges-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/coding-challenges-hs#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- gloss
- Data-Angle
- random

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  star-field:
    main:                starField.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - coding-challenges-hs

  snake:
    main:                snake.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - coding-challenges-hs

tests:
  coding-challenges-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coding-challenges-hs
